const translations = {
  en: {
    // App
    app: {
      title: "CreatorHub - Support Your Favorite Creators",
      description: "Subscription platform for creators and fans",
    },

    // Navbar
    nav: {
      feed: "Feed",
      discover: "Discover",
      dashboard: "Dashboard",
      newPost: "New post",
      homeFeed: "Home Feed",
      discoverCreators: "Discover creators",
      myPurchases: "My purchases",
      settings: "Settings",
      logout: "Logout",
      login: "Login",
      join: "Join",
      creator: "Creator",
      fan: "Fan",
      myAccount: "My Account",
    },

    // Home page
    home: {
      badge: "Platform for creators and fans",
      title1: "Support your",
      title2: "favorite creators",
      subtitle:
        "CreatorHub connects fans with creators through exclusive premium content. Subscribe, support and unlock amazing content.",
      goToDashboard: "Go to dashboard",
      joinNow: "Join now",
      signIn: "Sign in",
      creators: "Creators",
      fans: "Fans",
      content: "Content",
      howItWorks: "How it works",
      simpleWay: "Simple way to",
      support: "support",
      threeSteps: "Three simple steps to discover and support your favorite creators",
      discoverCreatorsTitle: "Discover creators",
      discoverCreatorsDesc: "Browse and find talented creators who share content you love",
      unlockPremium: "Unlock premium",
      unlockPremiumDesc: "Access exclusive premium content with a single click",
      supportCreators: "Support creators",
      supportCreatorsDesc: "Help your favorite creators thrive by supporting their work",
      forCreators: "For creators",
      earnFromPassion: "Earn from your",
      passion: "passion",
      creatorCTA:
        "Join as a creator to share exclusive content with your fans. Create free and premium posts to monetize your creativity.",
      becomeCreator: "Become a creator",
      subscriptions: "Subscriptions",
      monthlyRevenue: "Monthly revenue",
      premium: "Premium",
      paidContent: "Paid content",
      fansLabel: "Fans",
      buildCommunity: "Build community",
      control: "Control",
      yourRules: "Your rules",
      pocPlatform: "Platform · On-chain payments",
    },

    // Login
    login: {
      welcomeBack: "Welcome back",
      signInToAccount: "Sign in to your account",
      username: "Username",
      usernamePlaceholder: "Enter your username",
      password: "Password",
      passwordPlaceholder: "Enter your password",
      signInButton: "Sign in",
      signingIn: "Signing in...",
      noAccount: "Don't have an account?",
      register: "",
      loginFailed: "Login failed",
      invalidCredentials: "Invalid username or password.",
      welcomeBackToast: "Welcome back!",
      loggedInAs: "Logged in as",
    },

    // Creator Dashboard
    dashboard: {
      welcome: "Welcome,",
      manageAccount: "Manage your account and create amazing content",
      pricing: "Pricing",
      newPost: "New post",
      posts: "Posts",
      premium: "Premium",
      free: "Free",
      subscribers: "Subscribers",
      yourPosts: "Your posts",
      noPosts: "No posts",
      createFirstPostDesc: "Create your first post and start building your community!",
      createFirstPost: "Create first post",
      createNewPost: "New post",
      shareWithFans: "Share content with your fans",
      media: "Media",
      clickToAddMedia: "Click to add photo or video",
      mediaFormats: "PNG, JPG, GIF up to 10MB | MP4, WebM up to 50MB",
      selectMedia: "Please select an image or video file",
      videoTooLarge: "Video is too large. Maximum size is 50MB",
      gifTooLarge: "GIF is too large. Maximum size is 10MB",
      title: "Title",
      titlePlaceholder: "Add title...",
      description: "Description",
      descriptionPlaceholder: "What is this post about...",
      premiumContent: "Premium Content",
      requiresSubscription: "Requires subscription or purchase",
      priceLabel: "Post price",
      priceHint: "Enter 0 for a free post. Any other value makes the post premium.",
      willBePremium: "This post will require unlocking",
      postTags: "Post tags",
      postTagsHint: "Add tags describing this post's content (optional)",
      cancel: "Cancel",
      publish: "Publish",
      publishing: "Publishing...",
      published: "Published!",
      premiumPostLive: "Your premium post is now live!",
      postPublished: "Your post has been published!",
      pricingSettings: "Pricing settings",
      setSubscriptionPrice: "Set monthly subscription price",
      subscriptionPrice: "Subscription price",
      subscriptionPriceDesc: "Fans will pay this amount for unlimited access to your content",
      save: "Save",
      saved: "Saved",
      subscriptionPriceSet: "Subscription price set to",
      editPost: "Edit post",
      makeChanges: "Make changes and save",
      saveChanges: "Save changes",
      updated: "Updated",
      changesSaved: "Changes have been saved.",
      deletePost: "Delete post?",
      deleteConfirm: "Are you sure you want to delete",
      cannotUndo: "This action cannot be undone.",
      delete: "Delete",
      deleted: "Deleted",
      postDeleted: "Post has been deleted.",
      error: "Error",
      selectImage: "Please select an image file",
      fileTooLarge: "File is too large. Maximum size is 5MB",
      imageLoadFailed: "Failed to load image",
      noSubscriptions: "Subscriptions are disabled",
      // Profile settings
      profileSettings: "Profile settings",
      editProfile: "Edit profile",
      bio: "About me",
      bioPlaceholder: "Describe yourself and your content...",
      bioDesc: "Short description visible on your profile",
      tags: "Content tags",
      tagsDesc: "Select tags describing your content (18+)",
      selectTags: "Select tags...",
      selectedTags: "Selected tags",
      noTagsSelected: "No tags selected",
      profileUpdated: "Profile updated",
      profileSaved: "Your profile has been saved",
      adultContent: "Adult content",
      adultContentWarning: "This page contains content intended only for adults (18+)",
    },

    // Fan Home
    fanHome: {
      feed: "Feed",
      discover: "Discover",
      myPurchases: "My purchases",
      subscribing: "Subscribing",
      notSubscribingYet: "You're not subscribing to anyone yet",
      noContent: "No content",
      noContentDesc: "Creators haven't published any posts yet. Check back later!",
      discoverCreators: "Discover creators",
      suggestedCreators: "Suggested creators",
      seeAll: "See all",
      view: "View",
      trending: "Trending",
      newContent: "New content",
      exclusive: "Exclusive",
      behindScenes: "Behind the scenes",
      premiumContent: "Premium content",
      unlock: "Unlock",
      unlockToSee: "Unlock to view this content",
      unlocking: "Unlocking...",
      unlockFor: "Unlock for",
      unlocked: "Unlocked!",
      unlockedAccess: "You now have access to this premium content.",
      premiumUnlocked: "Premium - Unlocked",
      hoursAgo: "h ago",
      filterByTags: "Filter by tags",
      clearFilters: "Clear filters",
      noFilterResults: "No results",
      noFilterResultsDesc: "No posts found with selected tags. Try changing filters.",
      activeFilters: "Active filters",
      clearAll: "Clear all",
      enjoyContent: "Enjoy the content!",
    },

    // Payment / Wallet
    payment: {
      insufficientFunds: "Insufficient funds",
      insufficientFundsDesc:
        "You don't have enough funds in your account. Add funds to your wallet to continue.",
      yourBalance: "Your balance",
      required: "Required",
      difference: "Missing",
      addFunds: "Add funds",
      walletPayment: "Wallet payment",
      cryptoPayment: "x402 Crypto payment",
      selectPaymentMethod: "Select payment method",
      processing: "Processing payment...",
      success: "Payment successful!",
      failed: "Payment failed",
      tryAgain: "Try again",
    },

    // Connect Wallet
    wallet: {
      connectWallet: "Connect Wallet",
      connectWalletDesc: "Connect your crypto wallet to use x402 payments",
      walletRequired: "Wallet Required",
      walletRequiredDesc: "You need to connect a crypto wallet to continue this operation.",
      connecting: "Connecting...",
      connected: "Connected!",
      connectMetaMask: "Connect MetaMask",
      connectWalletConnect: "WalletConnect",
      connectCoinbase: "Coinbase Wallet",
      enterManually: "Or enter address manually",
      walletAddress: "Wallet Address",
      walletAddressPlaceholder: "0x...",
      invalidAddress: "Invalid wallet address",
      save: "Save",
      disconnect: "Disconnect wallet",
      yourWallet: "Your wallet",
      noWalletConnected: "No wallet connected",
      walletConnected: "Wallet connected",
      walletDisconnected: "Wallet disconnected",
    },

    // Creator Profile
    profile: {
      creatorNotFound: "Creator not found",
      creatorNotFoundDesc: "This creator doesn't exist or has been removed.",
      backToExplore: "Back to explore",
      creator: "Creator",
      joinedRecently: "Joined recently",
      posts: "posts",
      photos: "photos",
      premium: "premium",
      subscribed: "Subscribed",
      cancelSubscription: "Cancel subscription",
      cancelling: "Cancelling...",
      subscribe: "Subscribe",
      subscribeFor: "Subscription for",
      subscribing: "Subscribing...",
      all: "All",
      free: "Free",
      noPosts: "No posts",
      noPostsDesc: "This creator hasn't published any content yet.",
      noPostsOfType: "No posts",
      subscriptionActive: "Subscription active!",
      accessToAll: "You now have access to all content from",
      subscriptionCancelled: "Subscription cancelled",
      noAccessAnymore: "You no longer have access to premium content from",
    },

    // Explore
    explore: {
      title: "Discover",
      creators: "Creators",
      subtitle: "Find and support your favorite creators. Unlock exclusive premium content.",
      searchPlaceholder: "Search creators...",
      featuredCreators: "Featured creators",
      allCreators: "All creators",
      resultsFor: "Results for",
      noCreators: "No creators",
      noCreatorsDesc: "There are no creators on the platform yet. Check back later!",
      noResults: "No results",
      noResultsDesc: "No creators found matching",
      post: "post",
      posts: "posts",
    },

    // Purchases / Library
    purchases: {
      title: "My Library",
      subtitle: "View your purchased content and access history",
      noContent: "No content yet",
      noContentDesc:
        "You haven't purchased or subscribed to any content yet. Explore creators and discover amazing content!",
      discoverCreators: "Discover Creators",
      purchased: "Purchased",
      subscribed: "Subscribed",
      noPurchased: "No purchased posts",
      noPurchasedDesc: "You haven't purchased any individual posts yet.",
      noSubscriptions: "No subscriptions",
      noSubscriptionsDesc: "You haven't subscribed to any creators yet.",
      postsPurchased: "posts purchased",
      creatorsSubscribed: "creators subscribed",
      purchasedBadge: "Purchased",
      subscribedBadge: "Subscribed",
      by: "by",
      view: "View",
      viewProfile: "View Profile",
      recentPosts: "Recent posts:",
      morePosts: "more posts",
    },

    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      back: "Back",
      close: "Close",
      confirm: "Confirm",
      currency: "$",
      perMonth: "/month",
      priceFormat: "${{price}}",
      pricePerMonth: "${{price}}/month",
    },
  },
};

export const t = translations.en;


export const translateBio = (_username: string, originalBio: string): string => {
  return originalBio;
};

export const translatePost = (
  originalTitle: string,
  originalDescription: string
): { title: string; description: string } => {
  return { title: originalTitle, description: originalDescription };
};
